import AboutUs from "@/components/aboutUs";
import Stats from "@/components/stats";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <>
      <AboutUs />
      <Stats />
    </>
  );
}
