import ContactUs from "@/components/contactUs";

export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

export default function Contact() {
  return (
    <>
      <ContactUs />
    </>
  );
}
